CREATE TABLE STATUS_PAGAMENTO
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE TIPO_PAGAMENTO
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE PAGAMENTO
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    CPF_CNPJ          VARCHAR(255),
    TIPO_PAGAMENTO_ID BIGINT NOT NULL,
    NUM_CARTAO        VARCHAR(255),
    VALOR             DECIMAL(19, 2),
    STATUS_ID         BIGINT NOT NULL,
    CONSTRAINT fk_pagamento_tipo FOREIGN KEY (TIPO_PAGAMENTO_ID)
        REFERENCES TIPO_PAGAMENTO (ID),
    CONSTRAINT fk_pagamento_status FOREIGN KEY (STATUS_ID)
        REFERENCES STATUS_PAGAMENTO (ID)
);
